services:
  backend:
    image: ghcr.io/bonnemai/curvefitter:sha-5e3ecb3@sha256:9d2c7f978c15dda45399047bb61e7c7655a7508e69161550b1ff48803d427eee
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/bonnemai/curvefitter_ui:latest
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      STREAM_URL: http://backend:8000/curves/stream
      APP_ENV: prd
